name: Syntax Tree Updater
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-tree:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Generate Syntax Tree
        run: python scripts/generate_syntax_tree.py
      - name: Check for Changes
        id: check_changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add syntax-tree.json
          if git diff --cached --quiet; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else:
            echo "changed=true" >> $GITHUB_OUTPUT
      - name: Commit and Push
        if: steps.check_changes.outputs.changed == 'true'
        run: |
          git commit -m "Auto-update syntax tree"
          git push